 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/experts", type: :request do
  # Expert. As you add validations to Expert, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Expert.create! valid_attributes
      get experts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      expert = Expert.create! valid_attributes
      get expert_url(expert)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_expert_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      expert = Expert.create! valid_attributes
      get edit_expert_url(expert)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Expert" do
        expect {
          post experts_url, params: { expert: valid_attributes }
        }.to change(Expert, :count).by(1)
      end

      it "redirects to the created expert" do
        post experts_url, params: { expert: valid_attributes }
        expect(response).to redirect_to(expert_url(Expert.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Expert" do
        expect {
          post experts_url, params: { expert: invalid_attributes }
        }.to change(Expert, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post experts_url, params: { expert: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested expert" do
        expert = Expert.create! valid_attributes
        patch expert_url(expert), params: { expert: new_attributes }
        expert.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the expert" do
        expert = Expert.create! valid_attributes
        patch expert_url(expert), params: { expert: new_attributes }
        expert.reload
        expect(response).to redirect_to(expert_url(expert))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        expert = Expert.create! valid_attributes
        patch expert_url(expert), params: { expert: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested expert" do
      expert = Expert.create! valid_attributes
      expect {
        delete expert_url(expert)
      }.to change(Expert, :count).by(-1)
    end

    it "redirects to the experts list" do
      expert = Expert.create! valid_attributes
      delete expert_url(expert)
      expect(response).to redirect_to(experts_url)
    end
  end
end
